name: 'report'

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]
    paths:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  # cancel-in-progress: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diff-reports:
    runs-on: macos-latest
    steps:
      - name: echo
        run : echo ${{ github.ref }}
      # Checks-out current branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # Checks-out master and prepare git diff report
      - name: create git diff
        id: gitdiff
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          git rev-list --left-right --count ${{ github.event.pull_request.base.sha }}...${{ github.sha }}
          git rev-list --left-right --count ${{ github.event.pull_request.base.sha }}...${{ github.sha }} | awk '{if($1 > 0) print "Your branch is " $1 "commits behind of master. Please update your branch before continuing with your PR" else print}' > output.md
          cat output.md
          echo ::set-output name=diff::$(cat output.md)
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: output.md
          path: output.md
  post_comment:
    needs: [diff-reports]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download diff
        uses: actions/download-artifact@v2
        with:
          name: output.md
      # - name: Prepare comment
      #   run: "echo \"<details>\n <summary> Here's a diff of how these changes impact the classified ontology (on -simple file): </summary> \n\" > comment.md; cat simple-report.md >> comment.md"
      - name: Post reasoned comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../output.md"
