name: 'report'

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  # cancel-in-progress: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diff-reports:
    runs-on: macos-latest
    steps:
      - name: echo
        run : echo ${{ github.ref }}
      # Checks-out current branch
      - uses: actions/checkout@v2
      # Checks-out master and prepare git diff report
      - name: create git diff
        id: gitdiff
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          echo ${{ github.head_ref }}
          git fetch origin main ${{ github.event.pull_request.base.sha }}
          git rev-list --left-right --count main...${{ github.head_ref }} > simple-report.md
          cat simple-report.md
          echo ::set-output name=diff::$(cat simple-report.md)
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: simple-report.md
          path: src/ontology/simple-report.md
  post_comment:
    needs: [diff-reports]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reasoned diff
        uses: actions/download-artifact@v2
        with:
          name: simple-report.md
      - name: download check
        run: |
          pwd
          ls -l
      - name: Prepare reasoned comment
        run: "echo \"<details>\n <summary> Here's a diff of how these changes impact the classified ontology (on -simple file): </summary> \n\" > comment.md; cat simple-report.md >> comment.md"
      - name: Post reasoned comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../comment.md"
          identifier: "REASONED"
