name: 'wait for me'

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  # cancel-in-progress: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  diff-reports:
    runs-on: macos-latest
    steps:
      - name: lets keep them waiting
        run: sleep 5
